// src/source.js

import { LuLayoutDashboard } from "react-icons/lu";
import { FaMapMarkedAlt, FaRegBell, FaCog } from "react-icons/fa";
import { MdOutlineReport } from "react-icons/md";
import { BsTrash } from "react-icons/bs";
import { IoAnalyticsSharp } from "react-icons/io5";

export const routes = [
  {
    name: "Tableau de bord",
    path: "/dashboard",
    icon: LuLayoutDashboard,
    sub_routes: [
      {
        name: "Aperçu",
        path: "/dashboard",
        icon: IoAnalyticsSharp,
      },
    ],
  },
  {
    name: "Carte & Heatmap",
    path: "/CarteHeatmap",
    icon: FaMapMarkedAlt,
  },
  {
    name: "Signalement",
    path: "/report",
    icon: MdOutlineReport,
  },
  {
    name: "Alertes",
    path: "/alerts",
    icon: FaRegBell,
  },
  {
    name: "Gestion de collecte",
    path: "/collection",
    icon: BsTrash,
  },
  {
    name: "Paramètres",
    path: "/settings",
    icon: FaCog,
  },
];

export const products = [
  {
    id: 1,
    title: "Wireless Bluetooth Earbuds",
    category: "Electronics",
    brand: "SoundPro",
    price: 49.99,
    rating: 4.5,
    orders: 320,
  },
  {
    id: 2,
    title: "Stainless Steel Water Bottle",
    category: "Home & Kitchen",
    brand: "HydroMax",
    price: 19.99,
    rating: 4.7,
    orders: 560,
  },
  {
    id: 3,
    title: "Men's Running Shoes",
    category: "Footwear",
    brand: "StrideFit",
    price: 89.99,
    rating: 4.3,
    orders: 210,
  },
  {
    id: 4,
    title: "4K Ultra HD Smart TV",
    category: "Electronics",
    brand: "VisionTech",
    price: 599.99,
    rating: 4.6,
    orders: 150,
  },
  {
    id: 5,
    title: "Leather Office Chair",
    category: "Furniture",
    brand: "ComfortPlus",
    price: 129.99,
    rating: 4.4,
    orders: 85,
  },
  {
    id: 6,
    title: "Gaming Keyboard and Mouse Combo",
    category: "Electronics",
    brand: "GameZone",
    price: 74.99,
    rating: 4.8,
    orders: 450,
  },
  {
    id: 7,
    title: "Portable Power Bank 10000mAh",
    category: "Electronics",
    brand: "ChargeFast",
    price: 29.99,
    rating: 4.5,
    orders: 390,
  },
  {
    id: 8,
    title: "Organic Green Tea Pack",
    category: "Grocery",
    brand: "Nature's Bliss",
    price: 14.99,
    rating: 4.7,
    orders: 270,
  },
  {
    id: 9,
    title: "Yoga Mat with Carry Strap",
    category: "Fitness",
    brand: "FlexiGear",
    price: 24.99,
    rating: 4.6,
    orders: 310,
  },
  {
    id: 10,
    title: "Smartwatch with Heart Rate Monitor",
    category: "Electronics",
    brand: "WristTech",
    price: 99.99,
    rating: 4.3,
    orders: 180,
  },
  {
    id: 11,
    title: "Chef's Knife 8-inch",
    category: "Home & Kitchen",
    brand: "SharpEdge",
    price: 39.99,
    rating: 4.8,
    orders: 200,
  },
  {
    id: 12,
    title: "Wireless Noise Cancelling Headphones",
    category: "Electronics",
    brand: "SilentAudio",
    price: 149.99,
    rating: 4.5,
    orders: 175,
  },
  {
    id: 13,
    title: "Professional DSLR Camera",
    category: "Electronics",
    brand: "ShutterPro",
    price: 899.99,
    rating: 4.9,
    orders: 120,
  },
  {
    id: 14,
    title: "Ergonomic Laptop Stand",
    category: "Office Supplies",
    brand: "DeskEase",
    price: 34.99,
    rating: 4.6,
    orders: 400,
  },
  {
    id: 15,
    title: "Portable Camping Tent",
    category: "Outdoors",
    brand: "CampPro",
    price: 129.99,
    rating: 4.7,
    orders: 145,
  },
  {
    id: 16,
    title: "Digital Air Fryer",
    category: "Home & Kitchen",
    brand: "CrispyChef",
    price: 89.99,
    rating: 4.8,
    orders: 230,
  },
  {
    id: 17,
    title: "Electric Toothbrush",
    category: "Personal Care",
    brand: "SmileBright",
    price: 49.99,
    rating: 4.7,
    orders: 190,
  },
  {
    id: 18,
    title: "Cordless Vacuum Cleaner",
    category: "Home Appliances",
    brand: "DustAway",
    price: 159.99,
    rating: 4.6,
    orders: 300,
  },
  {
    id: 19,
    title: "Foldable Smartphone Stand",
    category: "Accessories",
    brand: "TechEase",
    price: 14.99,
    rating: 4.5,
    orders: 410,
  },
  {
    id: 20,
    title: "Multi-Purpose Backpack",
    category: "Fashion",
    brand: "UrbanTrail",
    price: 59.99,
    rating: 4.8,
    orders: 250,
  },
  {
    id: 21,
    title: "LED Desk Lamp with USB Charging",
    category: "Office Supplies",
    brand: "BrightLite",
    price: 29.99,
    rating: 4.7,
    orders: 340,
  },
  {
    id: 22,
    title: "Smart Thermostat",
    category: "Home Automation",
    brand: "EcoSmart",
    price: 149.99,
    rating: 4.6,
    orders: 180,
  },
  {
    id: 23,
    title: "Electric Kettle 1.7L",
    category: "Home & Kitchen",
    brand: "QuickBoil",
    price: 39.99,
    rating: 4.8,
    orders: 310,
  },
  {
    id: 24,
    title: "Noise-Cancelling Gaming Headset",
    category: "Electronics",
    brand: "GameTune",
    price: 69.99,
    rating: 4.5,
    orders: 280,
  },
  {
    id: 25,
    title: "Outdoor Solar String Lights",
    category: "Outdoors",
    brand: "EcoGlow",
    price: 24.99,
    rating: 4.7,
    orders: 400,
  },
];